version: "3.8"
services:
  pixoo-brdige:
    container_name: pixoo-bridge
    image: ghcr.io/simplyroba/pixoo-bridge:latest
    ports:
      - 4000:4000
    environment:
      PIXOO_BASE_URL: xxx.xxx.xxx.xxx
      #PIXOO_HEALTH_FORWARD: false
      UID: 1000
      GID: 1000
    restart: unless-stopped
